packages:
    - './cjs-builder'
    - './tsconfig'
    - './utilities'
    - './builder'
    - './creator'
    - './codemods/*'
    - './codemods/Feature Flags/*'
    - './codemods/Go/*'
    - './codemods/Java/*'
    - './codemods/cal.com/*'
    - './codemods/ember/5/*'
    - './codemods/immutable/0/*'
    - './codemods/immutable/4/*'
    - './codemods/intuita/*'
    - './codemods/msw/2/*'
    - './codemods/netlify-sdk/0.8.1/*'
    - './codemods/netlify-sdk/0.8.4/*'
    - './codemods/netlify-sdk/0.8.5/*'
    - './codemods/next-i18next/*'
    - './codemods/next/13/*'
    - './codemods/next/14/*'
    - './codemods/react-redux/0/*'
    - './codemods/react-router/4/*'
    - './codemods/react-router/6/*'
    - './codemods/react/*'
    - './codemods/redwoodjs/core/4/*'
    - './codemods/bullmq/*'
    - './codemods/vitest/*'
    - './codemods/antd/5/*'
